### ISSUE TITLE
Chromium version

### ISSUE THREAD

**Issue by trimechee** [Alex313031/quark-player#11]
Hello, I am testing Quark player and it is abosolumnet beautiful fast light brilliant ! 🥇 💯 

Just a suggestion, i notice that the chromium version used is 108 while the stable chromium version is 115, it will be great to have the new version of chromium, tahnk you !

**Comment by Alex313031** [comment]
@trimechee I have specifically used Electron 22.x.y, which is based on Chromium 108. This is to support Windows 7/8/8.1, and older Linux like Ubuntu 16.04.

**Comment by trimechee** [comment]
Interesting !yes the support of windows 7 is important, i understand :)
