### ISSUE TITLE
Downloader like VCap Downloader : browse web sites and capture/download videos with curl and FFmpeg integrated

### ISSUE THREAD

**Issue by trimechee** [Alex313031/quark-player#12]
Hello, I discovered a program that has an original and intelligent concept: make a web browser with the necessary tools natively integrated to download streaming video so no need for add on extensions and we avoid the censorship of stores which sometimes ban addon extensions....

VCap Downloader (VCapDL)

https://vcapdl.com/

unfortunately the program becomes limited after 30 days and you can't even download standard 480p videos anymore....

this donwloader has integrated curl:

https://curl.se/

and ffmpeg and others tools to make possible smooth donwload of streaming videos,  we know it is very complex and difficult, but we hope, if technically possible, it will be great awesome to have integrated donwloader in Quark player like, thank so much you!

EDIT : her some open source extensions addons and script that can help to downlaod video via our beloved the beautiful Quark Player :  

https://www.downthemall.org/

https://github.com/rowrawer/stream-detector
https://github.com/chandler-stimson/live-stream-downloader
https://github.com/meowcateatrat/elephant

https://github.com/inbasic/bulk-media-downloader/

https://xtremedownloadmanager.com/

https://motrix.app/

https://github.com/zaidka/cliget

https://openvideofs.github.io/
Dominik Sander
OpenVideo – ad-free streaming
https://addons.mozilla.org/fr/firefox/addon/openvideo/
https://chrome.google.com/webstore/detail/openvideo-%E2%80%93-ad-free-strea/dadggmdmhmfkpglkfpkjdmlendbkehoh/support

* scripts

https://github.com/Momo707577045/media-source-extract

https://greasyfork.org/en/scripts/445751-unlimited-downloader

Youtube Tools All in one local Download MP4, MP3 HIGT QUALITY without external service and more.

https://greasyfork.org/fr/scripts/460680-youtube-tools-all-in-one-local-download-mp3-mp4-higt-quality-return-dislikes-and-more

https://greasyfork.org/fr/scripts/423851-simple-youtube-age-restriction-bypass

https://greasyfork.org/fr/scripts/369400-local-youtube-downloader

https://greasyfork.org/fr/scripts/434936-%E5%B1%8F%E8%94%BD%E6%89%80%E6%9C%89youtube%E5%B9%BF%E5%91%8A-youtube-ad-blocker-block-all-ad-including-blocking-youtube-music

https://greasyfork.org/fr/scripts/34613-youtube-multi-downloader-yt1s-com-mp3-fhd-mp4-hd-sd-3gp-no-ads

Youtube-tools-extension

https://github.com/DeveloperMDCM/Youtube-tools-extension

https://github.com/DeveloperMDCM/Youtube-tools-extension

https://github.com/dabaisuv/Tampermonkey-Script
https://greasyfork.org/fr/users/901788-dabaisuv
Unlimited_downloader by dabaisuv
https://greasyfork.org/fr/scripts/445751-unlimited-downloader
https://www.v2ex.com/t/856510
https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md
https://github.com/Momo707577045/media-source-extract

https://greasyfork.org/fr/scripts/445751-unlimited-downloader/discussions/153131
https://greasyfork.org/en/scripts/420325-mse-dump-tools
https://greasyfork.org/en/users/724921-tgsan
https://greasyfork.org/en/scripts/18671-inject2download
https://github.com/acolwell/mse-tools
https://github.com/acolwell/msetools-js
https://segmentfault.com/a/1190000025182822
https://github.com/Momo707577045/tinypng-script-with-cache
https://github.com/Momo707577045
https://github.com/kanishka-linux/hlspy
https://github.com/selsta/hlsdl
https://github.com/video-dev/hls.js

**Comment by Alex313031** [comment]
@trimechee I will not implement this, as most of the services that quark player includes are paid streaming sites that use Widevine for content protection to prevent piracy, thus, there is no way to download the videos even if you were to include jdownloader code.

**Comment by trimechee** [comment]
We understand , thank you :) even i think we can use Quark Player to access warez sites... but  FDM and video download helper and get them all are sufficient powerful to donwload from warez sites....
