### ISSUE TITLE
Add easy custom url address config feature

### ISSUE THREAD

**Issue by trimechee** [Alex313031/quark-player#13]
Hello, i try to use our beloved Quark Palyer to play videos from sites like : 

https://french-anime.com/exclue/1243-jjjujutsu-kaisenn.html

https://v5.voiranime.com/anime/link-click-2/link-click-2-03-vostfr/

https://vostfree.ws/689-sayonara-no-asa-ni-yakusoku-no-hana-wo-kazarou-vf-ddl-streaming.html

and other sites, but unfortunately nothing happens, we would love to try this new electron app browser with streaming websites and see the impact on performance and battery and smooth playback compared to traditional web browsers, so it will be great to add easy configuration tool in order to add our custom url, thank you !

EDIT : Awesome ! I just found a trick to be able to access all the sites you want, just activate the google service in settings/enable/disable services and voila, you have the google search engine and you can access all the desired websites!! Thank you very much Mr Alex :)

**Comment by Alex313031** [comment]
@trimechee You can already use a custom URL. Go to 'Services' > 'Open Custom URL', or use the keyboard shortcut Ctrl + O
