### ISSUE TITLE
Dark mode extension or flag dark

### ISSUE THREAD

**Issue by trimechee** [Alex313031/quark-player#17]
Hello,  the dark mode saves energy and battery and sometimes we watch long videos on streaming sites which sometimes do not have a dark theme mode, so it will be great to implement this light extension in Quark player to dark web pages in streaming sites : 

https://github.com/m-khvoinitsky/dark-background-light-text-extension

 it is an extension for firefox but we can install addons extensions from the firefox store in google chrome through these extensions:

https://foxified.org/
https://crosspilot.io/
Chameleon
https://chrome.google.com/webstore/detail/chameleon/dmpojjilddefgnhiicjcmhbkjgbbclob
https://sereneblue.github.io/chameleon/

or just add an option to enable chromium's dark mode flag by default, thank you very much !

**Comment by Alex313031** [comment]
@trimechee Added. There is now a setting in "Settings" on the menu bar to toggle light/dark mode.

**Comment by trimechee** [comment]
Awesome !! 🥇 Thank you so much Mr @Alex313031 :)

**Comment by trimechee** [comment]
Great ! 🥇 and sorry Mr Alex @Alex313031 for having riddled you and flooded you with my many requests and questions! you are a very brilliant developer and your multiple projects and outstanding revolutionary software are a source of inspiration and motivation which improves our lives and makes it more joyful and comfortable, thank you very much :)
