### ISSUE TITLE
Dailymotion, russian platforms and webtor 

### ISSUE THREAD

**Issue by trimechee** [Alex313031/quark-player#18]
Hello, dailymoton is a famous streaming platform where you can find a lot of documentaries, replay....also many Russian sites have streaming videos that cannot be found on other sites, also webtor site is useful to transform the torrent into streaming, we hope they will be added, thank you !

https://www.dailymotion.com/fr

https://ok.ru/video

https://video.sibnet.ru/

https://rutube.ru/

https://www.myvi.tv/
http://www.otakustudio.tv/
https://www.myvi.top/
https://fs.myvi.ru/

https://webtor.io/#/

**Comment by Alex313031** [comment]
@trimechee I can add dailymotion, however, the other ones are not popular enough for me to add them. You can add them yourself, or use the "open custom url" feature.

**Comment by trimechee** [comment]
Hello Mr @Alex313031 ,thank you,  I have already tried custom url, nothing happens, there is a bug, russian platforms host a lot of content from streaming sites and censored content from other platforms, and Russia has just passed a law which allows Russia to legally pirate Western movies and TV series because the west no longer wants to sell it movies, so Russian platforms are the place to be and would become the most popular sites in the world

**Comment by Alex313031** [comment]
@trimechee See latest release

**Comment by trimechee** [comment]
Awesome ! Thank you so much, we are very greatful for all yours efforts to invent and enhance all these great softwares Mr Alex ! 💯 🥇
