### ISSUE TITLE
Add some hotkeys

### ISSUE THREAD

**Issue by MulverineX** [Alex313031/quark-player#2]
- [ ] Toggle frameless window
- [ ] Go to service picker page

**Comment by Alex313031** [comment]
@MulverineX Quark Player already has both of these. See the menus, it will show the hotkeys for stuff.

**Comment by MulverineX** [comment]
Could these please be documented in the README somewhere? After enabling frameless window there's no way to view the menu.

**Comment by Alex313031** [comment]
@MulverineX I could add a Ctrl+Alt+Help thing that will open a little table with all the shortcuts. That way you only have to remember that one.

**Comment by MulverineX** [comment]
That'd be great

**Comment by Alex313031** [comment]
@MulverineX Here you go!

1. Added to docs > https://github.com/Alex313031/quark-player/blob/master/docs/keyboard_shortcuts.md

2. New option in the menu "Shortcut Table", which can be opened by `Ctrl + Alt + H` (here "H" is meaning Help). This will open the new help.html which has a <table> element with a copy of the table in keyboard_shortcuts.md

**Comment by Alex313031** [comment]
@MulverineX Here you go! > https://github.com/Alex313031/quark-player/releases/tag/v3.1.7

I don't think I'm going to add "Custom themeing" But what I think I will add is four modes:

1.dark (default)
2. light
3. Use system preference (only applicable on MacOS 10.12+, Win 8.1+, or Linux GTK 3.28+
4. Some special wacky theme that I want to mimick Opera GX's "neon" theme

**Comment by MulverineX** [comment]
@Alex313031 the point behind custom theming is to apply styles to the services themselves, not to the Quark UI

**Comment by Alex313031** [comment]
@MulverineX Ohhhhh. Ok well, idk how to inject CSS into a page :( Maybe I can learn by looking it up

**Comment by MulverineX** [comment]
Thanks for the release
