### ISSUE TITLE
Pluto missing

### ISSUE THREAD

**Issue by big610** [Alex313031/quark-player#21]
Pluto last appeared in Version 3.1.9. No Mention in Release Notes and Home Page Screenshot indicates Pluto.
Also missing & never appeared, new added services Plex, Dailymotion, CuriosityStream.
Are you still needing & planning to use my macOS to Build?

**Comment by Alex313031** [comment]
@big610 This seemed to be an issue after upgrading to 3.10. What you should do is remove the user profile and then reinstall latest release.

If you don't know how to do that, tell me what platform you are running it on (or plan to run it on) and I can show u.

**Comment by big610** [comment]
Using Windows Portable. Where is User Profile located?
Services/Main Menu does not show  Plex, Dailymotion, CuriosityStream.
I've never been able to add Open Custom URL with any version.

**Comment by Alex313031** [comment]
@big610 On Windows, it should be at C:\Users\$USERNAME\AppData\Local\quark_player

(might be named Quark Player or quark-player but you get the idea)

Delete that folder and relaunch it. Also, if you are not truly using it portably, but just want to be able to urn it without installing it, I would suggest that the .zip would be better.

**Comment by big610** [comment]
Quark is not in AppData. Not hyphen, underscore. Roaming has:
quark-player & Quark Player. Deleting changes nothing, tried eliminating different combinations of both. Still Missing Pluto, & Open Custom URL.
I have both Portables.
C:\Users$USERNAME\AppData\Roaming\quark-player
C:\Users$USERNAME\AppData\Roaming\Quark Player

**Comment by Alex313031** [comment]
@big610 Sorry, you are right. Chromium based browsers use Local. Electron uses Roaming. After deleting both of those folders, uninstalling, and then reinstalling, you still have the issue?

I am unable to reproduce on my machine.
