### ISSUE TITLE
Even more furry porn…

### ISSUE THREAD

**Issue by Boberttt** [Alex313031/quark-player#34]
https://github.com/Alex313031/atom-ng/tree/master/packages/yiff/assets
https://github.com/Alex313031/beaker-ng/tree/master/app/userland/yiff/imgs
https://github.com/Alex313031/quark-player/blob/master/src/ui/imgs/catgirl_fridge.png

Can you remove your “Easter eggs” from the rest of your repos? I appreciate you removing the one from thorium and the website after about 20 people complained, but when you don’t remove it from the rest it makes it seem like you’re trying to hide something rather then fix it

**Comment by foco21** [comment]
i don't get how one "accidentally " merges this stuff into like 5 other repos?

**Comment by jovanzers** [comment]
> i don't get how one "accidentally " merges this stuff into like 5 other repos?

what an alibi

**Comment by memepods** [comment]
if you guys wont fix it, at least let us fork it and remove it ourselfs!

**Comment by Boberttt** [comment]
Everything accept the https://github.com/Alex313031/quark-player/blob/master/src/ui/imgs/catgirl_fridge.png has been removed, and github has marked the repositories as explicit
