### ISSUE TITLE
Add Paramount Plus as a service

### ISSUE THREAD

**Issue by fabiofs-br** [Alex313031/quark-player#7]
Can you add Paramount Plus (https://www.paramountplus.com) as one ot the supported services?

**Comment by Alex313031** [comment]
@fabiofs-br Yes.

**Comment by fabiofs-br** [comment]
Windows 11. But I also plan to use it on Linux.

**Comment by Alex313031** [comment]
@fabiofs-br Here you go! > https://github.com/Alex313031/quark-player/releases/tag/v3.1.8

**Comment by fabiofs-br** [comment]
Thanks @Alex313031 ! I already tested it and it works great.

**Comment by fabiofs-br** [comment]
Closing issue.
