### ISSUE TITLE
Working on it. Need a Mac to build.

### ISSUE THREAD

**Issue by big610** [Alex313031/quark-player#8]
I can provide remote access.

**Comment by Alex313031** [comment]
@big610 Nice!! I have every platform except MacOS.

Just to be a little nerd here, I'm gonna list lol.
Windows 3.1, 95, 98, NT 4, 2000, XP, 7, 10, 11.
Ubuntu, Debian, Arch.
ChromiumOS, ThoriumOS, and a Chromebook.
Android phone, iPhone 11.
Raspberry Pi, Arduino.
Fuschia OS in a VM, WebOS on a Pi 3B+.

I have MacOS High Sierra installed in virtualbox, but performance is absolutely dismal. It is not nearly fast enough to do any sort of development work.

For [Thorium](https://thorium.rocks/), I have @midzer compile the releases on his M1 Mac. However, he doesn't wanna help with my Electron projects.

So this would be useful, and I could start releasing Mac builds.

How would this work, are you talking about your personal Mac, or would it be a cloud instance.

**Comment by big610** [comment]
Remote connection. I am far away from you, need my unit, have all other versions on external drives Mojave & above.
Check thrift stores, for your area. 
Many developers using Electron, with mutiple operating systems, do just one macOS a year only, don't want to chase Electron constant builds.

**Comment by Alex313031** [comment]
@big610 Ok how do you wanna do the remote connection?

**Comment by big610** [comment]
Remote connect thru Open Source Software. 
HopToDesk https://www.hoptodesk.com/  Windows Portable 6.91 MB
rustdesk https://github.com/rustdesk/rustdesk Windows Portable 19.0 MB
Enter Remote ID. I have both installed Windows & Mac.

**Comment by Alex313031** [comment]
@big610 OK cool. Building will require installing python 3.9 and nodejs 16, is that ok?

Ok installed rustdesk on linux (my main dev platform and daily driver OS)

**Comment by big610** [comment]
Yes, I understand, I'm fine to help, install.

**Comment by Alex313031** [comment]
@big610 OK so now what? Should we chat somewhere else because Im assuming we will need to exchange a token/key or login information?

**Comment by big610** [comment]
Discord. Followed by edit post, if needed.

**Comment by Alex313031** [comment]
@big610 Ok whats your discord

**Comment by big610** [comment]
When you respond, I'll have a log in, so you have, then confirm more....

**Comment by Alex313031** [comment]
@big610 What do you mean?
When I respond?

**Comment by big610** [comment]
On Discord now: duplicate. I will allow.

**Comment by Alex313031** [comment]
@big610 How am I going to message you if I don't know your discord username

**Comment by Alex313031** [comment]
@big610 OK I messaged you there.
